spring.application.name=agendador-tarefas

spring.data.mongodb.uri=mongodb://mongo:27017/db_agendador

usuario.url=http://usuario-api:8080/usuarios

server.port=8081

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

