spring.application.name=agendador-tarefas
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=8081

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

